sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
cache: pip
env:
  matrix:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
matrix:
  fast_finish: true
  include:
  - env: TOXENV=flake8
    python: 3.7
  - env: TOXENV=isort
    python: 3.7
  - env: TOXENV=readme
    python: 3.7
  - env: TOXENV=check-manifest
    python: 3.7
  exclude:
  - python: 3.4
    env: DJANGO=2.1
  allow_failure:
  - env: DJANGO=master
install:
- travis_retry pip install -U pip tox-travis setuptools wheel
script:
- tox
notifications:
  email: false
  slack:
    secure: AQwY5MJkYTl7oriVEiTX/z4hKcQCyQHCDXKT1IuFshkQ6u3hYLFQ70T34dtWHoSiWhc88W7/454v22b7akPV/DSmBAeBvCYBk+WI3vPPO4wBcqLp9BnsVSDbt4PoRuuolnkkU2TgwgdhqaG8bhanPK2kkqQnUrl2E7GeoCmyBS1pa8FvQL9klVnxvOJzBPXJiy1aTkeWmcZ1OWmG56MpeHoBt1DWFwIxXWXe1vJmoXUw7jw+FoBag62JUSQid37iGt7MgJF80AyfNdVC/ei5Xb0qk/GrjI71a2hzrX5H+a62hpoYg6JI+KRGsf5Idas3IzH8Q1kIkyVRnYIx2gl7UA2FpboEWURY/FtXVWEeNO12vMXwjJ3U9DU+9Ts9doA/GBkL/q39gqSP+Bb29engs20rGPhsdIYQ2UXaXqzelcrZy6h8puwKRfT/mq9Qe1CX7bdw5KCxTJ8stZItTNrKT9LEIKQREe8JFguPl0B0SSeQSwKRjM1UUdPK9L2HYN463tcPg9X4vO5leFZCq2IvFMmTxA9RptXVAfeSG+3qHkv99kEygRIA/uavkoWlFeXlWj5tSBO9ZjFuW1gF+pPHziZ41Tx6dIvjPAS9o+mZXN1pN9m5kJm5TGfgWv0KOL1pXQpLQ34VzDJNNWIPxL2hQxqnonPdAwDzWZHHG1wbjnc=
