sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
cache: pip
env:
  matrix:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
matrix:
  fast_finish: true
  include:
  - env: TOXENV=flake8
    python: 3.7
  - env: TOXENV=isort
    python: 3.7
  - env: TOXENV=readme
    python: 3.7
  - env: TOXENV=check-manifest
    python: 3.7
  exclude:
  - python: 3.4
    env: DJANGO=2.1
  allow_failures:
  - env: DJANGO=master
install:
- travis_retry pip install -U pip tox-travis setuptools wheel
script:
- tox
notifications:
  email: false
  slack:
    rooms:
      secure: ETvbaveF5242tNbL/KVozpEZ38OJGI/EVot/27H45062BNSeNRHfSEwDvqdikr9pSpm0GMwRhf1djLtWx+xIauKF026e1AkTDhQfmnh+pDYYVOWz1m0oJ5UuR+cvoxWJ/sIeJgJ236VOSWGFxxkLBnyuAtRxw7R/wv/l4pj89maxFJ9gf6Ox32yVvIrgnQ352jySVooJdGlINVSRBU0ktOOUJodnwxcg6QTcc0EooHzFRCjUmEhA6QDCNnQ67rmTljVassIXWDJZTNbRGYV11d8RjH9WqyVn321WtFEeU6myjDoxRhtFqhZnRzSVYivwpaNh0tqzUpSebMUfj9ccPF/3KKtTXQr4ep+T3wobeHHQR6JhWqh2KHeTppzjyUm/m4AfUHtyb1tSMUHjVCuRuRgdwKVEnZws69G0rl80B44CC3oLH/S44m9SB0ATWkmRpkMHIxxiza/EbRC73PKqX+l/vn83DbtQveHD0cCj5mHlFikBxpvg+rOVCtNb083KimR7AwGE8L+8MyEXCrij8yKEpYrrpQqWiybPu929MqM6CoStDPROb9MosIugweiEHL82UsFptmsIYRGpMVOCv+fbZeouaV7DcygrOjq0PjD9AV9Iiul5EQfvWd9iJW9JTpiKlJWcuPlk0PBTydg/3fw+gKYdhQhYF6kaIbJsgsU=
