sudo: false
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
cache: pip
env:
  matrix:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
matrix:
  fast_finish: true
  include:
  - env: TOXENV=flake8
    python: 3.7
  - env: TOXENV=isort
    python: 3.7
  - env: TOXENV=readme
    python: 3.7
  - env: TOXENV=check-manifest
    python: 3.7
  allow_failures:
  - env: DJANGO=master
install:
- travis_retry pip install -U pip tox-travis setuptools wheel
script:
- tox
notifications:
  email: false
  slack:
    secure: N6CShvn/YaKhZ5aYwgKG/sMYb7A3x+vDquopgW8tSt29eKyD5Sw5mhyvFpl0zYnAsStkKKvec+bBb/M4xZYICL9/kJm++pW7HO5MKFNA7qORt8U4tWktq211o0L1pU9WxoDmfRZVcyrSQGibvCTYzFO0U/D1VCudE/UP9qLB4oqIL+5nGO+RxwcsAX4hDveLB+VrUU1DyOXYxlUowKdK9Hapy0hOVVA6nilCwlarJuvrj2DEbR1Ra3x1ZUUiwMcQ0sfqYLapZEk6+llzC2u7B+6CtIfsy+B1YrgqbiO24K71PXnGII1h9cC7a2OWDhwhuc81Vya6Ehl0vcj3NGLVaPiy3rdE8P9b/V8tFQQ3nk9S65eDl67dPA+A5cfMwhlV6kqbcH6XbA4dC8mppHaC1otr2p8U2Lry1d6ZTvsuTHBi3XpeAGs6RUgWChWm+1Uzbq6UYFhBj2XL8sJ1Coze1EH3GN/hXPlxGre7nGKbPzCmyK/ZC7vS6aZ3+FOaGImthY88LcaKGvuyEZplPpzxLNWn1ZDGgShyu6SQC0EhDv4DD2HBh5HJfAmHv1Ty3gwsIMu2btnuCMkYLusOV0pp/4udXg5bW4Xbi5j5Zf5bVvp8+jIlqaZtNN+gBIWfauZ4WzPtmV1IJv2BWrblu1S6MfN5yabLkJhSoE2k/E6g4zQ=
