name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"

      - name: install test tools
        run: pdm sync -d

      - name: run lint
        run: |
          pdm run pip list
          pdm run nox -t lint
