name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['style', 'security', 'readme', 'typing']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install hatch
        run: pip install hatch

      - name: Run lint:${{ matrix.env }}
        run: hatch run lint:${{ matrix.env }}
