name: Unit test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
      max-parallel: 2

    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: install test deps
        run: pdm sync -d

      - name: run test
        run: |
          python -V
          pdm list --graph
          pdm run nox -s test_dj32 test_dj40 test_dj41 test_djmain --python "${{ matrix.python-version }}"
